### ISSUE TITLE
Support React versions < 16.3.0

### ISSUE THREAD

**Issue by janezk7** [CharlesStover/reactn#60]
Throws error at Index.js (line 105): 
> "TypeError: object(...) is not a function" 

> 

when importing reactn in react version 16.0.0. When upgrading react to newest version (16.8.6), I was able to import without issues. Took me quite some time to figure it out since it says in your FAQ that reactn supports all react versions across the board. Apparently that's not the case.

**Comment by CharlesStover** [comment]
Thank you so much for bringing this to my attention. I'll try to address it as soon as I have time.

**Comment by vladopaets** [comment]
doesn't work in react 16.8. too

**Comment by vladopaets** [comment]
![image](https://user-images.githubusercontent.com/19553375/57235069-bdfe2e80-702a-11e9-8956-9fc5422354d7.png)

**Comment by vladopaets** [comment]
this issue appeared after importing `useDispatch` method

**Comment by CharlesStover** [comment]
`useDispatch` is in ReactN 2.0. For ReactN 1.0, just replace `useDispatch` with `useGlobal`.

**Comment by CharlesStover** [comment]
The documentation on GitHub is for 2.0.0, because the source code on GitHub is 2.0.0.
The documentation (currently) on NPM is for 1.0.0, because the package on NPM is 1.0.0.

Sorry for the confusion. `useDispatch` is not in 1.x.

_ReactN 2.0 is ready_ if you want to point to this GitHub repo. The only reason it isn't deployed is because TravisCI kicked the bucket when GitHub Pages were added to the repo. It will most likely be deployed this weekend.

**Comment by ryanvanderpol** [comment]
@CharlesStover cool, thanks for the clarification.  I'll use `master` for now and will keep my eyes peeled for the npm update!

**Comment by davidrenne** [comment]
I want to try reactn with version 15.4.2.  How could I possibly fork this for older versions we are stuck on in our application?  Is that ever going to be feasible to implement in the main repo here?  Or is it just not a priority.

**Comment by CharlesStover** [comment]
The only reason this hasn't been done is priority. There's not a lot of demand for pre-hooks React. It should be as simple as disabling Providers if the Context API doesn't exist. I'll look into it this weekend if I don't have time sooner.

**Comment by davidrenne** [comment]
Thanks @CharlesStover, this package looks like it could be my savior to avoiding learning redux/mobx fully.  I just cringe when I read all the boilerplate of redux and I try to follow a complicated redux application component in our software.  It can get quite hard to read redux vs. the simplicity of straight react setState or reactn's setGlobal.  I really enjoyed your medium read once I found a way to read it without paying medium.  ;-P

Ping me here if you get something you think could work for my version of react I am stuck on.  I upgraded everything to 16.8 in our application and its a nightmare to fix all the broken stuff, so I am stuck on 15.4.1 for the time being.

No rush at all, I am just looking for a simpler global store for lazy component communication.  Prop hell is never fun and I dont always want to setup a pub/sub websocket listener for everything either.

**Comment by CharlesStover** [comment]
This is passing unit tests for React 15.0+, but the real testing will need to be community-driven. Let me know if any bugs are discovered.

If you are using React < 16.8, you will not have access the `useDispatch` and `useGlobal` hooks.

If you are using React < 16.3, you will not have access to the `createProvider` Context API.

If you are using React < 15.3, the `PureComponent` export will just be a copy of the `Component` export.

I'm going to test on lower versions of React just to see how it goes, and I'll publish 2.1.6 immediately after to support earlier versions of React (pre-Context). 🙂

I'm sorry for the delay, and thank you all for the patience and support.

**Comment by davidrenne** [comment]
Thank you so much for everything!  Excited to try it out.
